#!/usr/bin/env bash

clear

export GREEN="\033[32m"
export RED="\033[31m"
export YELLOW="\033[33m"
export BLUE="\033[34m"
export BOLD="\033[1m"
export RESET="\033[0m"

section() {
    echo
    echo -e "${BOLD}${BLUE}== $1 ==${RESET}"
}

ok() {
    echo -e "${GREEN}OK${RESET}"
}

fail() {
    echo -e "${RED}FAIL${RESET}"
}

warn() {
    echo -e "${YELLOW}$1${RESET}"
}

MODULE_DIR="$HOME/.config/mydash/modules"

source "$MODULE_DIR/header.sh"
source "$MODULE_DIR/system.sh"
source "$MODULE_DIR/network.sh"
source "$MODULE_DIR/rclone.sh"
source "$MODULE_DIR/battery.sh"
source "$MODULE_DIR/logs.sh"
